export const form = document.querySelector('#search-form')
export const galleryEl = document.querySelector('.gallery')
export const loadBtn = document.querySelector('.load-more')
export const tittle = document.querySelector('.search-tittle')
export const footer = document.querySelector('footer')